source-dir: ./src
output-types: lcov
output-path: ./target/coverage/tests.lcov
binary-path: ./target/debug/deps/
branch: true
ignore-not-existing: true
filter: covered
prefix-dir: /home/runner/work/dynein/dynein
