on:
  pull_request:
    types: [opened, synchronize, reopened]

name: Code coverage

jobs:
  build_and_test:
    name: grcov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --bins --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - run: ls -l
      - uses: actions-rs/grcov@v0.1.5
      - uses: codecov/codecov-action@v3.1.3
        with:
          verbose: true
